swagger: '2.0'
info:
  title: z-blog
  description: | 
    z-blog: http://localhost:3000/
  version: 1.0.0
paths:

  # 用户部分 start
 
  /v1/users/{id}:
    get:
      tags:
        - user
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: id
          description: 用户ID
      description: 获取某用户的信息
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
    delete:
      tags:
        - user
      parameters:
        - in: header
          name: token
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: id
          description: 用户ID
      description: 删除用户
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  /v1/user/login:
    post:
      tags:
        - user
      description: 登录系统
      parameters:        
        - in: body
          name: body
          description: 用户信息
          schema:
            $ref: '#/definitions/userLogin'   
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  /v1/user:
    post:
      tags:
        - user
      description: 用户注册
      parameters:        
        - in: body
          name: body
          description: 用户信息
          schema:
            $ref: '#/definitions/createUser'   
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  /v1/blog:
    post:
      tags:
        - blog
      description: 新增文章
      parameters:        
        - in: body
          name: body
          description: 文章
          schema:
            $ref: '#/definitions/createBlog'   
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  /v1/blog/{id}:
    get:
      tags:
        - blog
      parameters:
        - in: path
          name: id
          description: 博客ID
      description: 获取某一博客
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
    delete:
      tags:
        - blog
      parameters:
        - in: path
          name: id
          description: 博客ID
      description: 删除博客
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  /v1/blogs:
    get:
      tags:
        - blog
      description: 获取某用户的信息
      responses:
        '200':
          description: ''
        '400':
          description: no enough input
  

definitions:
  userLogin:
    type: object
    properties:
      userName:
        type: string 
      password:
        type: string
  createUser:
    type: object
    properties:
      userName:
        type: string 
      password:
        type: string
      email:
        type: string
  userinfo:
    type: object
    properties:
      loginName:
        type: string
      nikeName:
        type: string
      email:
        type: string
      password:
        type: string
  createBlog:
    type: object
    properties:
      title: 
        type: string
      imgUrl: 
        type: string
      iconUrl: 
        type: string
      body: 
        type: string
      author: 
        type: string

tags:
  - name: user
    description: 用户相关API
  - name: blog
    description: 文章
  - name: favorites
    description: 收藏站点
  - name: account
    description: 账号管理
